name: team_sync prod deployment
# run when code is pushed to main branch
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    strategy:
      matrix:
        node-version: [20.10.0]

    env:
      NEXT_SITE_URL: ${{secrets.NEXT_SITE_URL}}
      DATABASE_URL: ${{secrets.DATABASE_URL}}
      EMAIL_SENDER: ${{secrets.EMAIL_SENDER}}
      SMTP_HOST: ${{secrets.SMTP_HOST}}
      SMTP_PASSWORD: ${{secrets.SMTP_PASSWORD}}
      SMTP_USER: ${{secrets.SMTP_USER}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: bun install

      - name: Build team_sync app
        run: bun run build

      - name: Clear source code folder
        run: |
          cd /home/yash
          rm -rf team_sync
          mkdir team_sync

      - name: Copy files for standalone next js app
        run: |
          cp -r ./public ./.next/standalone/public
          cp -r ./.next/static ./.next/standalone/.next/static
          cp -r ./.next/standalone/{*,.*} /home/yash/team_sync

      - name: Restart pm2
        run: pm2 restart team_sync
